### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by woodscn** [erdc-cm/proteus#399]
This seems like such an obvious bug that I'm assuming I must be doing something wrong. Nevertheless, here it is.

Build on OSX fails with error message "No rule to make target `stack/examples/proteus.darwin.yaml'".
It turns out that there IS a file in the pointed to directory named `stack/examples/proteus.Darwin.yaml'. Renaming this file to lowercase solves the problem, and the build appears to progress normally. 

The file name is drawn (in the Makefile) from python sys.platform, which is lowercase.

**Comment by cekees** [comment]
I wonder if something weird is going on with darwin's file system and git. I never can quite remember what the default file system is on OS X. It's somehow nieither case insensitive nor case sensitive.  @mfarthin is proteus.darwin.yaml shown with uppercase or lowercase D on your system? What is the output of 

```
python -c "import  sys;  print sys.platform"
```

That's what the file name is based on. On my system it says "linux2":)

**Comment by srobertp** [comment]
FYI, It is a lowercase darwin on my mac.

**Comment by mfarthin** [comment]
@cekees sorry for the delay in responding. I didn't have my mac with me all day. The output of `sys.platform` is lowercase `darwin` but the example file is `proteus.Darwin.yaml`. 

@woodscn do you want to change the capitalization and submit a pull request?

**Comment by woodscn** [comment]
I'd be happy to, but the build ended up failing for me later on, which makes me a bit reluctant, since I can't run the tests to make sure the fix works. 

I can start trying to debug that later, but it's probably best handled as a separate issue. Would you still like me to submit the PR, even untested? 
N





On Mon, May 23, 2016 at 8:57 PM -0700, "mfarthin" <notifications@github.com> wrote:












@cekees sorry for the delay in responding. I didn't have my mac with me all day. The output of sys.platform is lowercase darwin but the example file is proteus.Darwin.yaml. 



@woodscn do you want to change the capitalization and submit a pull request?

**Comment by mfarthin** [comment]
Yeah, it's probably better if we do the PR with a working install. I can update and make the name change.

**Comment by mfarthin** [comment]
I just submitted pull request #399 to hashstack's to fix the capitalization on `proteus/stable`. I also had to make a few other changes to get the stack to compile.

**Comment by cekees** [comment]
Thanks. I merged the hashstack PR. @woodscn, let  us know if you get a successful build so we can close this.

**Comment by woodscn** [comment]
The build still fails. It's checking out commit ed55f4e10f07eb0b85fa6a0d15f4d0e5104902c0 from hashstack, which is not the same as stable/proteus. Perhaps that's the source of the problem?

**Comment by mfarthin** [comment]
Yeah, can you change to the stack directory and update it to the latest stable/proteus branch and see if that works?

**Comment by woodscn** [comment]
Seems to solve that particular problem. Thanks!
